[2025-10-06T00:26:43.680+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api scheduled__2025-10-05T00:00:00+00:00 [queued]>
[2025-10-06T00:26:43.683+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api scheduled__2025-10-05T00:00:00+00:00 [queued]>
[2025-10-06T00:26:43.684+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-10-06T00:26:43.688+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2025-10-05 00:00:00+00:00
[2025-10-06T00:26:43.690+0000] {standard_task_runner.py:57} INFO - Started process 430 to run task
[2025-10-06T00:26:43.692+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'user_automation', 'stream_data_from_api', 'scheduled__2025-10-05T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmpp4xmb73_']
[2025-10-06T00:26:43.692+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask stream_data_from_api
[2025-10-06T00:26:43.712+0000] {task_command.py:410} INFO - Running <TaskInstance: user_automation.stream_data_from_api scheduled__2025-10-05T00:00:00+00:00 [running]> on host 430d1f3a9d81
[2025-10-06T00:26:43.741+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='user_automation' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2025-10-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-05T00:00:00+00:00'
[2025-10-06T00:26:44.205+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: connecting to broker:29092 [('172.18.0.5', 29092) IPv4]
[2025-10-06T00:26:44.213+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <checking_api_versions_recv> [IPv4 ('172.18.0.5', 29092)]>: Broker version identified as 2.6
[2025-10-06T00:26:44.214+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('172.18.0.5', 29092)]>: Connection complete.
[2025-10-06T00:26:44.546+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: connecting to broker:29092 [('172.18.0.5', 29092) IPv4]
[2025-10-06T00:26:44.547+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connected> [IPv4 ('172.18.0.5', 29092)]>: Connection complete.
[2025-10-06T00:26:44.547+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('172.18.0.5', 29092)]>: Closing connection. 
[2025-10-06T05:46:28.794+0000] {kafka_stream.py:61} ERROR - An error occured: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[2025-10-06T05:46:28.801+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-10-06T05:46:28.861+0000] {client_async.py:1148} INFO - Closing idle connection 1, last active 19183950 ms ago
[2025-10-06T05:46:28.861+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connected> [IPv4 ('172.18.0.5', 29092)]>: Closing connection. 
[2025-10-06T05:46:28.877+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=user_automation, task_id=stream_data_from_api, execution_date=20251005T000000, start_date=20251006T002643, end_date=20251006T054628
[2025-10-06T05:46:28.917+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-10-06T05:46:28.944+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-06T08:14:15.819+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api scheduled__2025-10-05T00:00:00+00:00 [queued]>
[2025-10-06T08:14:15.822+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api scheduled__2025-10-05T00:00:00+00:00 [queued]>
[2025-10-06T08:14:15.823+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-10-06T08:14:15.827+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2025-10-05 00:00:00+00:00
[2025-10-06T08:14:15.829+0000] {standard_task_runner.py:57} INFO - Started process 32 to run task
[2025-10-06T08:14:15.831+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'user_automation', 'stream_data_from_api', 'scheduled__2025-10-05T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmpausx8e6p']
[2025-10-06T08:14:15.832+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask stream_data_from_api
[2025-10-06T08:14:15.859+0000] {task_command.py:410} INFO - Running <TaskInstance: user_automation.stream_data_from_api scheduled__2025-10-05T00:00:00+00:00 [running]> on host b06bf3f6accc
[2025-10-06T08:14:15.897+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='user_automation' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2025-10-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-05T00:00:00+00:00'
[2025-10-06T08:14:16.456+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.18.0.8', 29092)]>: connecting to broker:29092 [('172.18.0.8', 29092) IPv4]
[2025-10-06T08:14:16.461+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <checking_api_versions_recv> [IPv4 ('172.18.0.8', 29092)]>: Broker version identified as 2.6
[2025-10-06T08:14:16.461+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('172.18.0.8', 29092)]>: Connection complete.
[2025-10-06T08:14:16.816+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connecting> [IPv4 ('172.18.0.8', 29092)]>: connecting to broker:29092 [('172.18.0.8', 29092) IPv4]
[2025-10-06T08:14:16.818+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connected> [IPv4 ('172.18.0.8', 29092)]>: Connection complete.
[2025-10-06T08:14:16.818+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('172.18.0.8', 29092)]>: Closing connection. 
[2025-10-06T08:14:16.838+0000] {cluster.py:313} WARNING - Topic users_created is not available during auto-create initialization
[2025-10-06T08:14:34.422+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:14:35.962+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:14:37.785+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:14:38.847+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:14:39.933+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:14:41.394+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:14:42.868+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:14:44.362+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:14:45.891+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:14:47.938+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:14:49.867+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:14:51.306+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:14:52.419+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:14:53.862+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:14:55.415+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:14:57.939+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:14:59.402+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:15:01.329+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:15:02.991+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:15:04.941+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:15:06.412+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:15:07.918+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:15:09.387+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:15:10.871+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:15:12.332+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:15:13.434+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:15:14.913+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:15:16.551+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connected> [IPv4 ('172.18.0.8', 29092)]>: Closing connection. 
[2025-10-06T08:15:16.557+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-10-06T08:15:16.602+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=user_automation, task_id=stream_data_from_api, execution_date=20251005T000000, start_date=20251006T081415, end_date=20251006T081516
[2025-10-06T08:15:16.653+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-10-06T08:15:16.670+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-06T08:55:49.408+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api scheduled__2025-10-05T00:00:00+00:00 [queued]>
[2025-10-06T08:55:49.411+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api scheduled__2025-10-05T00:00:00+00:00 [queued]>
[2025-10-06T08:55:49.411+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-10-06T08:55:49.418+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2025-10-05 00:00:00+00:00
[2025-10-06T08:55:49.419+0000] {standard_task_runner.py:57} INFO - Started process 31 to run task
[2025-10-06T08:55:49.422+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'user_automation', 'stream_data_from_api', 'scheduled__2025-10-05T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmpho8d28wb']
[2025-10-06T08:55:49.423+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask stream_data_from_api
[2025-10-06T08:55:49.454+0000] {task_command.py:410} INFO - Running <TaskInstance: user_automation.stream_data_from_api scheduled__2025-10-05T00:00:00+00:00 [running]> on host b4e1875897bf
[2025-10-06T08:55:49.491+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='user_automation' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2025-10-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-05T00:00:00+00:00'
[2025-10-06T08:55:50.078+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.18.0.7', 29092)]>: connecting to broker:29092 [('172.18.0.7', 29092) IPv4]
[2025-10-06T08:55:50.084+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <checking_api_versions_recv> [IPv4 ('172.18.0.7', 29092)]>: Broker version identified as 2.6
[2025-10-06T08:55:50.084+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('172.18.0.7', 29092)]>: Connection complete.
[2025-10-06T08:55:50.441+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connecting> [IPv4 ('172.18.0.7', 29092)]>: connecting to broker:29092 [('172.18.0.7', 29092) IPv4]
[2025-10-06T08:55:50.443+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connected> [IPv4 ('172.18.0.7', 29092)]>: Connection complete.
[2025-10-06T08:55:50.443+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('172.18.0.7', 29092)]>: Closing connection. 
[2025-10-06T08:55:50.480+0000] {cluster.py:313} WARNING - Topic users_created is not available during auto-create initialization
[2025-10-06T08:56:11.042+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:56:12.509+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:56:14.482+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:56:16.097+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:56:17.964+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:56:18.997+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:56:20.498+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:56:22.031+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:56:23.554+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:56:24.997+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:56:26.947+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:56:28.006+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:56:29.438+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:56:30.499+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:56:32.030+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:56:34.472+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:56:35.537+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:56:36.985+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:56:38.509+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:56:39.925+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:56:41.002+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:56:42.559+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:56:43.989+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:56:45.567+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:56:48.045+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:56:49.582+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:56:50.303+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connected> [IPv4 ('172.18.0.7', 29092)]>: Closing connection. 
[2025-10-06T08:56:50.305+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-10-06T08:56:50.325+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=user_automation, task_id=stream_data_from_api, execution_date=20251005T000000, start_date=20251006T085549, end_date=20251006T085650
[2025-10-06T08:56:50.379+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-10-06T08:56:50.397+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-06T09:24:36.955+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api scheduled__2025-10-05T00:00:00+00:00 [queued]>
[2025-10-06T09:24:36.961+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api scheduled__2025-10-05T00:00:00+00:00 [queued]>
[2025-10-06T09:24:36.961+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-10-06T09:24:36.969+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2025-10-05 00:00:00+00:00
[2025-10-06T09:24:36.974+0000] {standard_task_runner.py:57} INFO - Started process 50 to run task
[2025-10-06T09:24:36.979+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'user_automation', 'stream_data_from_api', 'scheduled__2025-10-05T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmp9uzvtlh3']
[2025-10-06T09:24:36.980+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask stream_data_from_api
[2025-10-06T09:24:37.019+0000] {task_command.py:410} INFO - Running <TaskInstance: user_automation.stream_data_from_api scheduled__2025-10-05T00:00:00+00:00 [running]> on host bf3be0b6e359
[2025-10-06T09:24:37.068+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='user_automation' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2025-10-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-05T00:00:00+00:00'
[2025-10-06T09:24:37.594+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.18.0.7', 29092)]>: connecting to broker:29092 [('172.18.0.7', 29092) IPv4]
[2025-10-06T09:24:37.609+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <checking_api_versions_recv> [IPv4 ('172.18.0.7', 29092)]>: Broker version identified as 2.6
[2025-10-06T09:24:37.609+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('172.18.0.7', 29092)]>: Connection complete.
[2025-10-06T09:24:38.005+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connecting> [IPv4 ('172.18.0.7', 29092)]>: connecting to broker:29092 [('172.18.0.7', 29092) IPv4]
[2025-10-06T09:24:38.006+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connected> [IPv4 ('172.18.0.7', 29092)]>: Connection complete.
[2025-10-06T09:24:38.006+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('172.18.0.7', 29092)]>: Closing connection. 
[2025-10-06T09:24:38.024+0000] {cluster.py:313} WARNING - Topic users_created is not available during auto-create initialization
[2025-10-06T09:24:53.963+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:24:55.010+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:24:56.524+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:24:58.079+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:25:00.038+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:25:01.521+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:25:03.077+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:25:04.519+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:25:05.961+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:25:07.164+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:25:09.485+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:25:10.499+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:25:11.611+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:25:13.079+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:25:15.456+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:25:16.552+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:25:18.088+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:25:19.522+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:25:21.012+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:25:22.518+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:25:24.053+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:25:28.032+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:25:29.522+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:25:31.108+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:25:32.987+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:25:34.515+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:25:36.018+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:25:37.649+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connected> [IPv4 ('172.18.0.7', 29092)]>: Closing connection. 
[2025-10-06T09:25:37.660+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-10-06T09:25:37.704+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=user_automation, task_id=stream_data_from_api, execution_date=20251005T000000, start_date=20251006T092436, end_date=20251006T092537
[2025-10-06T09:25:37.759+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-10-06T09:25:37.781+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-06T09:42:40.171+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api scheduled__2025-10-05T00:00:00+00:00 [queued]>
[2025-10-06T09:42:40.175+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api scheduled__2025-10-05T00:00:00+00:00 [queued]>
[2025-10-06T09:42:40.175+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-10-06T09:42:40.179+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2025-10-05 00:00:00+00:00
[2025-10-06T09:42:40.181+0000] {standard_task_runner.py:57} INFO - Started process 57 to run task
[2025-10-06T09:42:40.183+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'user_automation', 'stream_data_from_api', 'scheduled__2025-10-05T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmpf3rocbxd']
[2025-10-06T09:42:40.184+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask stream_data_from_api
[2025-10-06T09:42:40.226+0000] {task_command.py:410} INFO - Running <TaskInstance: user_automation.stream_data_from_api scheduled__2025-10-05T00:00:00+00:00 [running]> on host 24002ed0955a
[2025-10-06T09:42:40.276+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='user_automation' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2025-10-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-05T00:00:00+00:00'
[2025-10-06T09:42:40.894+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.18.0.7', 29092)]>: connecting to broker:29092 [('172.18.0.7', 29092) IPv4]
[2025-10-06T09:42:40.906+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <checking_api_versions_recv> [IPv4 ('172.18.0.7', 29092)]>: Broker version identified as 2.6
[2025-10-06T09:42:40.906+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('172.18.0.7', 29092)]>: Connection complete.
[2025-10-06T09:42:41.257+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connecting> [IPv4 ('172.18.0.7', 29092)]>: connecting to broker:29092 [('172.18.0.7', 29092) IPv4]
[2025-10-06T09:42:41.257+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connected> [IPv4 ('172.18.0.7', 29092)]>: Connection complete.
[2025-10-06T09:42:41.257+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('172.18.0.7', 29092)]>: Closing connection. 
[2025-10-06T09:42:41.274+0000] {cluster.py:313} WARNING - Topic users_created is not available during auto-create initialization
[2025-10-06T09:42:59.747+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:43:00.856+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:43:02.743+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:43:04.306+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:43:05.844+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:43:07.775+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:43:09.241+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:43:14.849+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:43:16.304+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:43:17.751+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:43:18.820+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:43:20.827+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:43:22.278+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:43:23.869+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:43:25.339+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:43:27.281+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:43:29.309+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:43:30.844+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:43:32.848+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:43:34.311+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:43:36.310+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:43:38.766+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:43:40.271+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:43:41.003+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connected> [IPv4 ('172.18.0.7', 29092)]>: Closing connection. 
[2025-10-06T09:43:41.006+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-10-06T09:43:41.034+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=user_automation, task_id=stream_data_from_api, execution_date=20251005T000000, start_date=20251006T094240, end_date=20251006T094341
[2025-10-06T09:43:41.082+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-10-06T09:43:41.117+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
