[2025-10-05T12:06:04.795+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api manual__2025-10-05T12:06:02.627458+00:00 [queued]>
[2025-10-05T12:06:04.799+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api manual__2025-10-05T12:06:02.627458+00:00 [queued]>
[2025-10-05T12:06:04.799+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-10-05T12:06:04.804+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2025-10-05 12:06:02.627458+00:00
[2025-10-05T12:06:04.808+0000] {standard_task_runner.py:57} INFO - Started process 37 to run task
[2025-10-05T12:06:04.812+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'user_automation', 'stream_data_from_api', 'manual__2025-10-05T12:06:02.627458+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmpdfth7q8g']
[2025-10-05T12:06:04.813+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask stream_data_from_api
[2025-10-05T12:06:04.870+0000] {task_command.py:410} INFO - Running <TaskInstance: user_automation.stream_data_from_api manual__2025-10-05T12:06:02.627458+00:00 [running]> on host 430d1f3a9d81
[2025-10-05T12:06:04.924+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='user_automation' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2025-10-05T12:06:02.627458+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-05T12:06:02.627458+00:00'
[2025-10-05T12:06:05.627+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: connecting to broker:29092 [('172.18.0.5', 29092) IPv4]
[2025-10-05T12:06:05.653+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <checking_api_versions_recv> [IPv4 ('172.18.0.5', 29092)]>: Broker version identified as 2.6
[2025-10-05T12:06:05.653+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('172.18.0.5', 29092)]>: Connection complete.
[2025-10-05T12:06:06.009+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connecting> [IPv4 ('172.18.0.5', 29092)]>: connecting to broker:29092 [('172.18.0.5', 29092) IPv4]
[2025-10-05T12:06:06.010+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connected> [IPv4 ('172.18.0.5', 29092)]>: Connection complete.
[2025-10-05T12:06:06.010+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('172.18.0.5', 29092)]>: Closing connection. 
[2025-10-05T12:06:06.046+0000] {cluster.py:313} WARNING - Topic users_created is not available during auto-create initialization
[2025-10-05T12:06:20.104+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-05T12:06:22.031+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-05T12:06:23.660+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-05T12:06:25.604+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-05T12:06:27.137+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-05T12:06:31.606+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-05T12:06:35.071+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-05T12:06:36.658+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-05T12:06:38.503+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-05T12:06:40.117+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-05T12:06:41.553+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-05T12:06:43.034+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-05T12:06:44.506+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-05T12:06:46.083+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-05T12:06:47.621+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-05T12:06:49.564+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-05T12:06:51.609+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-05T12:06:54.972+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-05T12:06:56.026+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-05T12:06:57.110+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-05T12:07:00.590+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-05T12:07:03.009+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-05T12:07:04.103+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-05T12:07:05.641+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-05T12:07:06.005+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connected> [IPv4 ('172.18.0.5', 29092)]>: Closing connection. 
[2025-10-05T12:07:06.007+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-10-05T12:07:06.037+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=user_automation, task_id=stream_data_from_api, execution_date=20251005T120602, start_date=20251005T120604, end_date=20251005T120706
[2025-10-05T12:07:06.060+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-10-05T12:07:06.073+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
